FROM node:14-alpine

# curl needed to display Heroku release logs
RUN apk --no-cache add curl

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install

COPY . /app

# env is passing from /home/ec2-user/shared/...
# COPY .env.example /app/.env

RUN yarn build

ENTRYPOINT ["scripts/docker_setup_init_prod.sh"]

# CMD yarn start:prod
