### Get assets - no params
GET http://localhost:3001/assets HTTP/1.1
Content-Type: application/json
Cookie: key=first-value

### Get asset
GET http://localhost:3001/assets/4 HTTP/1.1
Content-Type: application/json
Cookie: key=first-value

### Get asset - not found
GET http://localhost:3001/assets/0 HTTP/1.1
Content-Type: application/json
Cookie: key=first-value

### Invalid asset
POST http://localhost:3001/assets HTTP/1.1
Content-Type: application/json
Cookie: key=first-value

{
  "attrs": {
    "scAddress": "Foo",
    "scId": "Foo",
    "cTitle": "Foo"
  }
}

### OK asset
POST http://localhost:3001/assets HTTP/1.1
Content-Type: application/json
Cookie: key=first-value

{
  "attrs": {
    "scAddress": "0x12345E3C0baAB3E08CdfD552C960A1050f373042",
    "scId": "Foo",
    "cTitle": "cTitle",
    "cStatus": "cStatus",
    "landType": "landType",
    "landArea": 155,
    "propertyType": "propertyType",
    "propertyArea": "propertyArea",
    "beds": 2,
    "bedrooms": 2,
    "roomsTotal": 2,
    "kitchens": 1,
    "livingRooms": 3,
    "terraces": 0,
    "balconies": 2,
    "garages": 1,
    "bathRooms": 2,
    "occupation": "occupation",
    "images": ["images"],
    "saleDocuments": ["saleDocuments"],
    "agreementIntent": ["doc"],
    "sellingAgreement": ["doc"],
    "llcPropertyDocuments": ["doc"],
    "ownershipAgreement": ["doc"],
    "tokenizationAgreement": ["doc"],
    "llcFormationDocument": ["doc"],
    "notaryConclusion": ["doc"],
    "managementDocuments": ["doc"],
    "rentalAgreement": ["doc"],
    "averageCoCPercentage": 12,
    "projectedIrrPercentage": 12,
    "taxesPercentage": 1,
    "insurancePercentage": 0,
    "propertyManagementPercentage": 12,
    "utilitiesPercentage": 12,
    "llcAdministrationFeePercentage": 12
  }
}
