version: '3.1'
services:
  postgres:
    image: postgres:bullseye
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - database_postgres:/var/lib/postgresql
volumes:
  database_postgres:
